### ISSUE TITLE
Website final mockup design 

### ISSUE THREAD

**Issue by wuryantoAji** [wuryantoAji/cits5505GroupProject#9]
finalize the design for this website in this figma
https://www.figma.com/file/5ueSt8LvLgPj1m5GAhcp6Z/Mockup?type=design&node-id=0%3A1&mode=design&t=iIaTaBnsCtYh5upm-1

**Comment by SoleilGU** [comment]
Hi, Aji @wuryantoAji . As the list of reassigned tasks on teams, I'm responsible for the design of all pages.
![Screenshot 2024-05-08 170641](https://github.com/wuryantoAji/cits5505GroupProject/assets/147923030/ad972dd2-105c-4051-a983-40ed661eebaf)
So I'm wondering if it is possible to remove others from this task? Or can we divide this task into two parts, like 1. a 'basic flow' or 'basic functionality' section; 2. a 'web design' section.
And we also have a 404 page function that needs to be added to issues.

**Comment by wuryantoAji** [comment]
Yup, already removed

**Comment by wuryantoAji** [comment]
great job
